echo "Applying Policy A"
python sim/sim_d2.py 5 policyA
echo "Done window 5"
python sim/sim_d2.py 15 policyA
echo "Done window 15"
python sim/sim_d2.py 25 policyA
echo "Done window 25"
python sim/sim_d2.py 30 policyA
echo "Done window 30"
python sim/sim_d2.py 35 policyA
echo "Done window 35"

echo "Applying Policy E"
python sim/sim_d2.py 5 policyE
echo "Done window 5"
python sim/sim_d2.py 15 policyE
echo "Done window 15"
python sim/sim_d2.py 25 policyE
echo "Done window 25"
python sim/sim_d2.py 30 policyE
echo "Done window 30"
python sim/sim_d2.py 35 policyE
echo "Done window 35"

echo "Applying Policy R"
python sim/sim_d2.py 5 policyR
echo "Done window 5"
python sim/sim_d2.py 15 policyR
echo "Done window 15"
python sim/sim_d2.py 25 policyR
echo "Done window 25"
python sim/sim_d2.py 30 policyR
echo "Done window 30"
python sim/sim_d2.py 35 policyR
echo "Done window 35"

echo "Applying Policy M"
python sim/sim_d2.py 5 policyM
echo "Done window 5"
python sim/sim_d2.py 15 policyM
echo "Done window 15"
python sim/sim_d2.py 25 policyM
echo "Done window 25"
python sim/sim_d2.py 30 policyM
echo "Done window 30"
python sim/sim_d2.py 35 policyM
echo "Done window 35"

echo "Applying Policy N"
python sim/sim_d2.py 5 policyN
echo "Done window 5"
python sim/sim_d2.py 15 policyN
echo "Done window 15"
python sim/sim_d2.py 25 policyN
echo "Done window 25"
python sim/sim_d2.py 30 policyN
echo "Done window 30"
python sim/sim_d2.py 35 policyN
echo "Done window 35"